# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tips',
                'managed': False,
            },
        ),
    ]
