# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'managed': False, 'verbose_name_plural': 'tips'},
        ),
    ]
