# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20170604_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
            ],
            options={
                'db_table': 'texts',
                'managed': False,
                'verbose_name_plural': 'textos',
            },
        ),
    ]
